[project]
name = "david-seismic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zsk4", email = "zachary_katz@mines.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "astropy>=7.2.0",
    "cartopy>=0.25.0",
    "dask[array]>=2025.12.0",
    "gdal==3.4.*",
    "geopandas>=1.1.1",
    "gstools>=1.7.0",
    "impdar>=1.2.1",
    "ipykernel>=7.0.1",
    "matplotlib>=3.10.7",
    "obspy>=1.4.2",
    "openpyxl>=3.1.5",
    "pdemtools>=1.2.1",
    "pyastronomy>=0.24.0",
    "pykrige>=1.7.3",
    "pyshp>=3.0.2.post1",
    "pystac-client>=0.9.0",
    "scikit-learn>=1.7.2",
    "segyio>=1.9.13",
    "shapely>=2.1.2",
    "sliderule>=5.0.1",
    "xarray[complete,io]>=2025.10.1",
]

[project.scripts]
david-seismic = "david_seismic:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
